### ISSUE TITLE
Multi User Support

### ISSUE THREAD

**Issue by TheBricktop** [icosa-foundation/open-brush#163]
Hello, 
im thinking about adding networking to openbrush, probably using mirror networking or something easier like osc for starters. 
How one could tackle synchronizing the painting area? By recording brush moves and passing them as a series of vectors with params or as a obj string?

**Comment by gabrieldevsouza** [comment]
Is this still in progress?

**Comment by mikeskydev** [comment]
Absolutely 😀

**Comment by mikeskydev** [comment]
The baseline pass of the multiplayer stack has been implemented, so I'm going to close this in favor of mini issues for the remaining tasks!
