### ISSUE TITLE
where to find similar mesh(es) for pop-up windows, menu, etc.? (Just a query)

### ISSUE THREAD

**Issue by addy1997** [icosa-foundation/open-brush#568]
Hi there,

I tried this app on my Meta Quest 3 and the fonts, meshes for the menu, windows, etc., are impressive. It works smoothly. 
Where can I find similar meshes and fonts?

**Comment by mikeskydev** [comment]
Hi, it's all very custom to the app I'm afraid! I'd love to extract it into its own UI package, but as we've found the code is very heavily integrated into the function and state of the rest of the app, so it's a project in itself.

**Comment by addy1997** [comment]
> Hi, it's all very custom to the app I'm afraid! I'd love to extract it into its own UI package, but as we've found the ui code and assets are very heavily integrated into the function and state of the rest of the app, so it's a project in itself.

Thanks for your reply. So, you mean that it's all custom-built from scratch? Which tool do you use to develop 3D UI models?

**Comment by mikeskydev** [comment]
Yes! We inherited this project from Google, so I'm not sure who made the original UI or what tooling they used, I'm afraid. it's really simple though, just a rounded tube with an outline effect material.
