### ISSUE TITLE
Adding Google service API support issue

### ISSUE THREAD

**Issue by chengnay** [icosa-foundation/open-brush#616]
Hi,
After following the steps for Google service API support,
I found out that there is no "Other" to select for "Creating an OAuth credential".
![image](https://github.com/icosa-foundation/open-brush/assets/33050705/422a9a2e-a9de-4eb1-b4f3-96ebf5d008d2)
Cannot select "Other", I am not able to get Client Secret.

How should I resolve this issue?

**Comment by chengnay** [comment]
After searching online, I found this [link](https://stackoverflow.com/questions/61984699/how-to-create-application-type-other-in-oauth-client-id-in-google) and manage to solve the issue.
Other is changed to Desktop App.

Please help to update the guideline, thanks!

**Comment by andybak** [comment]
Thanks for figuring that out. Fixed in #618
