### ISSUE TITLE
The drawing is invisible in passthrough

### ISSUE THREAD

**Issue by Qionted** [icosa-foundation/open-brush#803]
Drawings are invisible when you go into a passthrough environment. Menus and controllers are still visible, and you can still draw. Drawings become visible again when you go to any environment other than passthrough.

Quest 3 standalone
I tried 2.9.5 and 2.9.14 and the issue persisted in both.

**Comment by mikeskydev** [comment]
Are you on quest firmware v72? Hearing similar things from other MR game devs

**Comment by Qionted** [comment]
Yes I am running v72. Yes not all brushes. Here are the brushes that are invisible:
- Highlighter
- Soft Highlighter
- Light
- Fire
- Embers
- Smoke
- Snow
- Rainbow
- Stars
- Velvet Ink
- Waveform
- Coarse Bristles
- Electricity
- Streamers
- Bubbles
- Hyper Grid
- Chromatic Wave
- Dots
- Comet

**Comment by mikeskydev** [comment]
Yep, all the ones I expected, thanks for the thorough list! It appears this is a bug in the latest firmware and only affects some users, I have v72 and my brushes are fine annoyingly! I'll keep this issue open and let you know when Meta tells us it's resolved.

**Comment by Qionted** [comment]
You are a legend!

**Comment by mikeskydev** [comment]
@Qionted out of curiosity and seeing as you have a github account, feel free to try sideloading the quest artefact from https://github.com/icosa-foundation/open-brush/actions/runs/12376364854 if the brushes work in this version, it's another useful datapoint I can pass along.

**Comment by mikeskydev** [comment]
@Qionted supposedly this has been fixed by Meta, either by a new update or by deleting that specific PTC firmware you're on. Try and update, otherwise you may have to format or wait for the next version!

**Comment by Venthe** [comment]
@mikeskydev another datapoint; v72 has issues.

**Comment by mikeskydev** [comment]
@Qionted @Venthe Had some more information from another user, try this!

```
Figured this out: The Content Adaptive Brightness Control experimental on 3/3S seems to break compositor layers with transparency in MR apps.

Turn this setting off in Settings > Advanced, or Settings > Experimental

```

**Comment by Venthe** [comment]
@mikeskydev can confirm, this is a workaround that makes OpenBrush visible in passthrough once again

**Comment by mikeskydev** [comment]
Thanks! I love it when Meta breaks existing apps with experiments... 😅
